### ISSUE TITLE
No contact info

### ISSUE THREAD

**Issue by knitlybak** [carlbarrdahl/carlbarrdahl#1]
Hello,

I came across your profile at the next github and I would like to reach out for a potential collaboration but I can't seem to find your contact info (email etc).

Thanks,
Ioannis

**Comment by carlbarrdahl** [comment]
Thank you @knitlybak! :pray: 
I've updated the resume and feel free to contact me at carlbarrdahl@gmail.com

Looking forward hearing from you!
